name: ScLoad
main: me.aricius.scload.ScLoad
version: 0.2.3
depend: [WorldEdit]
author: [ Aricius, fromgate, Exemplive ]
api-version: 1.19
commands:
  scload:
    aliases: [scl]
    description: ScLoad command
    usage: |
      /scload load <filename>
      /scload load <filename> <world>
      /scload reload
      /scload cfg

